### ISSUE TITLE
Fix new messages counters [Batch 5/8]

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-web#1347]
There are some issues with the counters (see more details in the comments below):

- [x] daostack/common-web#1664

- [x] daostack/common-web#1665

- [ ]     ~~Feed counter doesn't always work (need details)~~

- [x] daostack/common-backend#1891

- [x] daostack/common-backend#1892

- [x] daostack/common-backend#1893

- [x] daostack/common-web#1669

- [x] #1673

![Image](https://github.com/daostack/common-web/assets/129174316/219c276d-46a9-40c5-b77d-a0a674fa1799)

(notion ticket [here](https://www.notion.so/daostack/I-get-updates-new-messages-indicator-on-streams-I-ve-created-608af5ca521f4ef3846e389fa337f6b8?pvs=4))
